import "./globals.css";
import "primereact/resources/themes/md-light-deeppurple/theme.css";
import "primeicons/primeicons.css";

import { PrimeReactProvider } from "primereact/api";
import Tailwind from "primereact/passthrough/tailwind";
import { Inter } from "next/font/google";

import localFont from "next/font/local";

const araboto = localFont({
  src: [
    {
      path: "../public/fonts/Araboto/ArabotoThin400.ttf",
      style: "normal",
      weight: "100",
    },
    {
      path: "../public/fonts/Araboto/ArabotoNormal400.ttf",
      style: "normal",
      weight: "400",
    },
    {
      path: "../public/fonts/Araboto/ArabotoMedium400.ttf",
      style: "medium",
      weight: "500",
    },
    {
      path: "../public/fonts/Araboto/ArabotoLight400.ttf",
      style: "normal",
      weight: "300",
    },
    {
      path: "../public/fonts/Araboto/ArabotoBold400.ttf",
      style: "normal",
      weight: "700",
    },
    {
      path: "../public/fonts/Araboto/ArabotoBlack400.ttf",
      style: "normal",
      weight: "900",
    },
  ],
  variable: "--font-araboto",
});

const helvetica = localFont({
  src: [
    {
      path: "../public/fonts/Helvetica/Helvetica400.ttf",
    },
  ],
  variable: "--font-helvetica",
});

const helveticaNeue = localFont({
  src: [
    {
      path: "../public/fonts/HelveticaNeue/HelveticaNeueLT65Medium450.ttf",
      style: "normal",
      weight: "400",
    },
  ],
  variable: "--font-helvetica-neue",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="pt-BR"
      className={`${inter.variable} ${araboto.variable} ${helvetica.variable} ${helveticaNeue.variable}`}
    >
      <PrimeReactProvider
        value={{
          appendTo: "self",
          hideOverlaysOnDocumentScrolling: true,
          // unstyled: true,
          pt: Tailwind,
        }}
      >
        <body className="pt-10">{children}</body>
      </PrimeReactProvider>
    </html>
  );
}
